application:
  xml-url: https://n35ro2ic4d.execute-api.eu-central-1.amazonaws.com/prod/engine-rest/process-definition/key/invoice/xml
  path-finder-strategy: RANDOM # check org.camunda.bpm.diagramtraverser.pathfinder.StrategyName for more strategies